#!/usr/bin/env bash
set -euo pipefail

APP_NAME="Discord Team Hub"
ENV_FILE=".env"
DEFAULT_GITHUB_REPO_NAME="7thC"
DEFAULT_GITHUB_BRANCH="work"

if [[ -t 0 ]]; then
  PROMPT_INPUT="/dev/stdin"
elif [[ -r /dev/tty ]]; then
  PROMPT_INPUT="/dev/tty"
else
  echo "This installer needs an interactive terminal so it can ask for setup values." >&2
  exit 1
fi

say() {
  printf '\n\033[1m%s\033[0m\n' "$*" > /dev/tty
}

note() {
  printf '  %s\n' "$*" > /dev/tty
}

prompt_required() {
  local var_name="$1"
  local label="$2"
  local value=""

  while [[ -z "$value" ]]; do
    printf '%s: ' "$label" > /dev/tty
    IFS= read -r value < "$PROMPT_INPUT"
    if [[ -z "$value" ]]; then
      note "$var_name is required."
    fi
  done

  printf '%s' "$value"
}

prompt_default() {
  local label="$1"
  local default_value="$2"
  local value=""

  printf '%s [%s]: ' "$label" "$default_value" > /dev/tty
  IFS= read -r value < "$PROMPT_INPUT"
  printf '%s' "${value:-$default_value}"
}

prompt_secret() {
  local label="$1"
  local value=""

  if [[ -r /dev/urandom ]]; then
    value="$(LC_ALL=C tr -dc 'A-Fa-f0-9' < /dev/urandom | head -c 64 || true)"
  fi

  if [[ -z "$value" ]] && command -v openssl >/dev/null 2>&1; then
    value="$(openssl rand -hex 32)"
  fi

  if [[ -z "$value" ]]; then
    value="$(prompt_required SESSION_SECRET "$label")"
  else
    printf '%s [auto-generated, press Enter to keep]: ' "$label" > /dev/tty
    local entered=""
    IFS= read -r entered < "$PROMPT_INPUT"
    value="${entered:-$value}"
  fi

  printf '%s' "$value"
}

prompt_yes_no() {
  local label="$1"
  local default_value="$2"
  local answer=""
  local suffix="[y/N]"

  if [[ "$default_value" == "y" ]]; then
    suffix="[Y/n]"
  fi

  while true; do
    printf '%s %s: ' "$label" "$suffix" > /dev/tty
    IFS= read -r answer < "$PROMPT_INPUT"
    answer="${answer:-$default_value}"
    case "${answer,,}" in
      y|yes) return 0 ;;
      n|no) return 1 ;;
      *) note "Please answer yes or no." ;;
    esac
  done
}

write_env() {
  local client_id="$1"
  local client_secret="$2"
  local bot_token="$3"
  local guild_id="$4"
  local public_url="$5"
  local port="$6"
  local session_secret="$7"
  local data_file="$8"

  if [[ -f "$ENV_FILE" ]]; then
    if prompt_yes_no "$ENV_FILE already exists. Back it up and replace it?" "n"; then
      cp "$ENV_FILE" "$ENV_FILE.backup.$(date +%Y%m%d%H%M%S)"
    else
      note "Leaving existing $ENV_FILE unchanged."
      return 0
    fi
  fi

  cat > "$ENV_FILE" <<ENV
# Generated by install.sh for $APP_NAME
DISCORD_CLIENT_ID=$client_id
DISCORD_CLIENT_SECRET=$client_secret
DISCORD_BOT_TOKEN=$bot_token
DISCORD_GUILD_ID=$guild_id
PUBLIC_URL=$public_url
PORT=$port
SESSION_SECRET=$session_secret
DATA_FILE=$data_file
ENV

  chmod 600 "$ENV_FILE"
  note "Wrote $ENV_FILE with mode 600."
}

run_local_setup() {
  if [[ ! -f package.json ]]; then
    note "package.json was not found. Run this installer from the repository directory before local setup."
    return 0
  fi

  if ! command -v npm >/dev/null 2>&1; then
    note "npm was not found. Install Node.js 20+ and then run: npm install && npm run build"
    return 0
  fi

  local node_major="0"
  if command -v node >/dev/null 2>&1; then
    node_major="$(node -p "Number(process.versions.node.split('.')[0])" 2>/dev/null || echo 0)"
  fi

  if (( node_major < 20 )); then
    note "Node.js 20+ is required. Current major version: $node_major"
    note "Install Node.js 20+ and then run: npm install && npm run build"
    return 0
  fi

  say "Installing Node dependencies"
  npm install

  say "Building the app"
  npm run build
}



resolve_repo_url() {
  local repo_url="${DISCORD_TEAM_HUB_REPO_URL:-}"
  if [[ -n "$repo_url" ]]; then
    printf '%s' "$repo_url"
    return 0
  fi

  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    local name_with_owner=""
    name_with_owner="$(gh repo list --limit 200 --json name,nameWithOwner --jq ".[] | select(.name == \"$DEFAULT_GITHUB_REPO_NAME\") | .nameWithOwner" | head -n 1 || true)"
    if [[ -n "$name_with_owner" ]]; then
      printf 'https://github.com/%s.git' "$name_with_owner"
      return 0
    fi
  fi

  prompt_required DISCORD_TEAM_HUB_REPO_URL "GitHub repository clone URL"
}

ensure_repo_checkout() {
  if [[ -f package.json && -f src/index.ts && -f install.sh ]]; then
    return 0
  fi

  say "Repository checkout needed"
  note "The installer was run outside the app repository, so it needs to clone the private repo first."

  if ! command -v git >/dev/null 2>&1; then
    note "git was not found. Install git, then rerun the GitHub one-line installer."
    exit 1
  fi

  local repo_url=""
  local branch="${DISCORD_TEAM_HUB_BRANCH:-$DEFAULT_GITHUB_BRANCH}"
  local install_dir="${DISCORD_TEAM_HUB_DIR:-$HOME/discord-team-hub}"

  repo_url="$(resolve_repo_url)"
  local repo_url="${DISCORD_TEAM_HUB_REPO_URL:-}"
  local branch="${DISCORD_TEAM_HUB_BRANCH:-}"
  local install_dir="${DISCORD_TEAM_HUB_DIR:-$HOME/discord-team-hub}"

  if [[ -z "$repo_url" ]]; then
    repo_url="$(prompt_required DISCORD_TEAM_HUB_REPO_URL "GitHub repository clone URL")"
  fi

  install_dir="$(prompt_default "Install directory" "$install_dir")"

  if [[ -d "$install_dir/.git" ]]; then
    say "Updating existing checkout"
    git -C "$install_dir" fetch --all --prune
    if [[ -n "$branch" ]]; then
      git -C "$install_dir" checkout "$branch"
      git -C "$install_dir" pull --ff-only origin "$branch"
    else
      git -C "$install_dir" pull --ff-only
    fi
  else
    if [[ -e "$install_dir" ]]; then
      note "$install_dir already exists but is not a git checkout. Choose a different DISCORD_TEAM_HUB_DIR or remove it."
      exit 1
    fi

    say "Cloning app repository"
    if [[ -n "$branch" ]]; then
      git clone --branch "$branch" "$repo_url" "$install_dir"
    else
      git clone "$repo_url" "$install_dir"
    fi
  fi

  if [[ ! -f "$install_dir/install.sh" ]]; then
    note "The cloned repository does not contain install.sh. Check DISCORD_TEAM_HUB_REPO_URL and DISCORD_TEAM_HUB_BRANCH."
    exit 1
  fi

  chmod +x "$install_dir/install.sh"
  say "Continuing setup from $install_dir"
  cd "$install_dir"
  exec ./install.sh
}

run_docker_setup() {
  if [[ ! -f docker-compose.yml ]]; then
    note "docker-compose.yml was not found. Run this installer from the repository directory before Docker setup."
    return 0
  fi

  if ! command -v docker >/dev/null 2>&1; then
    note "Docker was not found. Install Docker, then run: docker compose up -d --build"
    return 0
  fi

  say "Building and starting Docker service"
  docker compose up -d --build
}

say "$APP_NAME installer"
ensure_repo_checkout
note "This will ask for Discord OAuth/bot settings and generate $ENV_FILE."
note "Create the Discord application first, then set its redirect URL to: PUBLIC_URL/auth/discord/callback"

client_id="$(prompt_required DISCORD_CLIENT_ID "Discord client/application ID")"
client_secret="$(prompt_required DISCORD_CLIENT_SECRET "Discord client secret")"
bot_token="$(prompt_required DISCORD_BOT_TOKEN "Discord bot token")"
guild_id="$(prompt_required DISCORD_GUILD_ID "Discord server/guild ID")"
public_url="$(prompt_default "Public website URL" "http://localhost:3000")"
port="$(prompt_default "HTTP port" "3000")"
data_file="$(prompt_default "Data file path" "./data/store.json")"
session_secret="$(prompt_secret "Session secret")"

write_env "$client_id" "$client_secret" "$bot_token" "$guild_id" "$public_url" "$port" "$session_secret" "$data_file"

say "Choose how to finish setup"
if prompt_yes_no "Run dependency install/build or Docker setup now?" "y"; then
  if prompt_yes_no "Use Docker Compose now?" "n"; then
    run_docker_setup
  else
    run_local_setup
  fi
else
  note "Skipped install/build. You can run npm install && npm run build or docker compose up -d --build later."
fi

say "Setup complete"
note "Discord OAuth redirect URL: ${public_url%/}/auth/discord/callback"
note "Start locally with: npm run dev"
note "Start compiled app with: npm start"
note "Start Docker service with: docker compose up -d --build"
